spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db-url}
    username: ${db-username}
    password: ${db-password}
  jpa:
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

jwt:
  secret-key: ${jwt-key}

oauth:
  kakao:
    url:
      auth: https://kauth.kakao.com
      api: https://kapi.kakao.com
  google:
    url:
      auth: https://oauth2.googleapis.com
      api: https://www.googleapis.com

client:
  mapbox:
    key: ${mapbox-key}
  seoul:
    key: ${seoul-key}
