GET https://kauth.kakao.com/oauth/authorize?client_id=e5a4437c4ab721d1a8dd1b685a244afb&
    redirect_uri={{context_path}}/oauth/kakao&response_type=code

###
POST {{context_path}}/oauth/kakao
Content-Type: application/json


{
  "grantType": "authorization_code",
  "clientId": "e5a4437c4ab721d1a8dd1b685a244afb",
  "redirectUri": "{{context_path}}/oauth/kakao",
  "authorizationCode": "qRJ3cbZA8SMlUX-P5uz4fxzOrRap0TrBmbDQ26OgIqd7Pju5-4LwF2b8mG_f9h1hm8zwgAo9c5oAAAGJgRnNpQ"
}


> {%
    client.global.set("access_token", response.body.accessToken);
    client.global.set("refresh_token", response.body.refreshToken);
%}


###
POST {{context_path}}/place
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "name": "현석이네",
  "longitude": 127.40118103,
  "latitude": 37.40810019
}

###
DELETE {{context_path}}/place?favoriteId=1
Authorization: Bearer {{access_token}}

###
GET {{context_path}}/place
Authorization: Bearer {{access_token}}
