GET https://kauth.kakao.com/oauth/authorize?client_id=e5a4437c4ab721d1a8dd1b685a244afb&
    redirect_uri=http://localhost:8080/oauth/kakao&response_type=code

###
POST http://localhost:8080/oauth/kakao
Content-Type: application/json


{
  "grantType": "authorization_code",
  "clientId": "e5a4437c4ab721d1a8dd1b685a244afb",
  "redirectUri": "http://localhost:8080/oauth/kakao",
  "authorizationCode": "5acywOg6TwcoVH1PPTkELH0c4kcU--2dGoOc9WL7x0YxcGmmWm3fL6dUOLijoQ7I4qdJ_go9dVoAAAGJTJrNnA"
}


> {%
    client.global.set("access_token", response.body.accessToken);
    client.global.set("refresh_token", response.body.refreshToken);
%}


###
POST localhost:8080/place
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "longitude": 127.10118103,
  "latitude": 37.60810019,
  "type": "NORMAL"
}

###
DELETE http://localhost:8080/place?favoriteId=3
Authorization: Bearer {{access_token}}

###
GET  localhost:8080/place
Authorization: Bearer {{access_token}}
