GET https://kauth.kakao.com/oauth/authorize?client_id=e5a4437c4ab721d1a8dd1b685a244afb&
    redirect_uri=http://localhost:8080/oauth/kakao&response_type=code

###
POST http://localhost:8080/oauth/kakao
Content-Type: application/json


{
  "grantType": "authorization_code",
  "clientId": "e5a4437c4ab721d1a8dd1b685a244afb",
  "redirectUri": "http://localhost:8080/oauth/kakao",
  "authorizationCode": "lHKeXM9KtXxiXC_s1y5tdwW57R-SItOD-HRZbeaP4aCMp1kOH9vTdd_Bzgg9LP2vQfNTTgopyNoAAAGJPgpiQA"
}


> {%
    client.global.set("access_token", response.body.data.accessToken);
    client.global.set("refresh_token", response.body.data.refreshToken);
%}


###
POST localhost:8080/place/add
Content-Type: application/json
Authorization: Bearer {{access_token}}

{
  "longitude": 127.10118103,
  "latitude": 37.60810089,
  "type": "NORMAL"
}


###
GET  localhost:8080/place/find
Authorization: Bearer {{access_token}}
