GET https://kauth.kakao.com/oauth/authorize?client_id=e5a4437c4ab721d1a8dd1b685a244afb&
    redirect_uri={{context_path}}/oauth/kakao&response_type=code

###
POST {{context_path}}/oauth/kakao
Content-Type: application/json

{
  "grantType": "authorization_code",
  "clientId": "e5a4437c4ab721d1a8dd1b685a244afb",
  "redirectUri": "{{context_path}}/oauth/kakao",
  "authorizationCode": "R4NKugGbSeE7tRD-Uv3LuUSts9BCVTRNNqDmmKfNadyoRDchyA1ChS2JmkX5X2o1uo-REwo9dJkAAAGJTNBqmA"
}

> {%
    client.global.set("access_token", response.body.accessToken);
    client.global.set("refresh_token", response.body.refreshToken);
%}

###
DELETE {{context_path}}/member
Authorization: Bearer {{access_token}}
