### 전체 대여소의 실시간 자전거 대수를 반환합니다.
GET {{context_path}}/route/station

### 대여소의 실시간 자전거 대수를 레디스에 업데이트합니다.
POST {{context_path}}/route/station

###

### 출발지와 도착지의 좌표를 기반으로 대여소 2곳을 포함한 경로를 안내합니다.
### Pedestrian: 도보, Cyclability: 자전거
### 도보, 자전거, 도보 순으로 안내합니다.
POST {{context_path}}/route/cycle
Content-Type: application/json

{
  "startLatitude": "37.4864406",
  "startLongitude": "127.1030211",
  "endLatitude": "37.553001",
  "endLongitude": "126.924558"
}


